### ISSUE TITLE
For "Login" endpoint, using "POST" method will be more approriate

### ISSUE THREAD

**Issue by jamilxt** [piashcse/ktor-E-Commerce#1]
https://github.com/piashcse/ktor-E-Commerce/blob/1dea3596494bfc2d16d4e1ec93ec15e1cb29cb1c/src/main/kotlin/com/piashcse/route/UserRoute.kt#L22

**Comment by piashcse** [comment]
Fixed and updated accordingly 
Ref:
https://github.com/piashcse/ktor-E-Commerce/pull/22
