### ISSUE TITLE
Renaming "User" to "Customer" will be more appropriate

### ISSUE THREAD

**Issue by jamilxt** [piashcse/ktor-E-Commerce#2]
https://github.com/piashcse/ktor-E-Commerce/blob/1dea3596494bfc2d16d4e1ec93ec15e1cb29cb1c/README.md?plain=1#L94C1-L94C1

**Comment by piashcse** [comment]
Renamed user role to customer role as it is more understandable and meaningful

Ref:
https://github.com/piashcse/ktor-E-Commerce/commit/d0cee49786a82c534f0d6e94f0f3de5dcd999bc8

https://github.com/piashcse/ktor-E-Commerce/commit/1e8946d234d0b1fd436bbf77de9e2682a5e3d555

**Comment by piashcse** [comment]
Done
